### ISSUE TITLE
questions about the help command

### ISSUE THREAD

**Issue by pingu6** [InterStella0/starlight-dpy#12]
how to hide help command from help command?
also is there way to remove `start_button` and `end_button`? idk but for small bots it won't be needed

**Comment by InterStella0** [comment]
Yes, hiding help command is discord.py built-in. Removing start_button/end_button, assuming this is MenuHelpCommand, you can provide your own mapping to `pagination_buttons` kwargs in your constructor, 
```py
class MyMenuHelpCommand(startlight.MenuHelpCommand):
    def __init__(self, *args, **kwargs):
        row = 1 # your button placement
        super().__init__(*args, 
            command_attrs={'hidden': True},
            pagination_buttons={
                'previous_button': discord.ui.Button(emoji="◀️", row=row),
                'stop_button': discord.ui.Button(emoji="⏹️", row=row),
                'next_button': discord.ui.Button(emoji="▶️", row=row),
            }, **kwargs)
```

**Comment by pingu6** [comment]
> Yes, hiding help command is discord.py built-in. Removing start_button/end_button, assuming this is MenuHelpCommand, you can provide your own mapping to `pagination_buttons` kwargs in your constructor,
> 
> ```python
> class MyMenuHelpCommand(startlight.MenuHelpCommand):
>     def __init__(self, *args, **kwargs):
>         row = 1 # your button placement
>         super().__init__(*args, 
>             command_attrs={'hidden': True},
>             pagination_buttons={
>                 'previous_button': discord.ui.Button(emoji="◀️", row=row),
>                 'stop_button': discord.ui.Button(emoji="⏹️", row=row),
>                 'next_button': discord.ui.Button(emoji="▶️", row=row),
>             }, **kwargs)
> ```
doesn't work: 
![image](https://github.com/InterStella0/starlight-dpy/assets/106933377/db87c246-1da3-4825-9075-63b183c2ad6d)
![image](https://github.com/InterStella0/starlight-dpy/assets/106933377/33668eee-816e-4acc-b161-b5247199307d)

**Comment by InterStella0** [comment]
My mistake, you should set the missing key to None for it to remove it, otherwise it will be replaced with an existing button. 
```py
class MyMenuHelpCommand(startlight.MenuHelpCommand):
    def __init__(self, *args, **kwargs):
        row = 1 # your button placement
        super().__init__(*args, 
            command_attrs={'hidden': True},
            pagination_buttons={
                'start_button': None,
                'end_button': None,
                'previous_button': discord.ui.Button(emoji="◀️", row=row),
                'stop_button': discord.ui.Button(emoji="⏹️", row=row),
                'next_button': discord.ui.Button(emoji="▶️", row=row),
            }, **kwargs)
```
