### ISSUE TITLE
Implementation questions - large sharded bot

### ISSUE THREAD

**Issue by skylarr1227** [InterStella0/starlight-dpy#2]
I couldnt find your contact information for discord anywhere on here, so sorry if this is the wrong place to request it-I run a recently rebranded (still large) discord bot and am thinking about possibly using this within our project as help is something ive never really put a whole lot of time into, and ours is just static....

However, our bot has the max commands registered globally and many sub-command groups... the project is quite a large project. Would you mind contacting me on discord to discuss this a bit more? 
skylarr#6666
if you have time of course-if not ill figure it out <3

**Comment by InterStella0** [comment]
I don't give my personal contact information for numerous reasons. However, you could ask for a simple Q&A on the Discussion tab relating to the library. Though personally, I wouldn't use this library for a large production bot, as of now, it's still in drafting stages depending on how I feel about an implementation. I may change it if I found a better UI/UX for the library.
